version: "3"
services:
  flask:
    container_name: flask
    hostname: flask
    build: ./backend
    tty:  true
    volumes:
      - ./backend:/backend
    ports:
      - 3030:3030
  react:
    container_name: react
    hostname: react
    build: ./frontend
    tty:  true
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 3000:3000